# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_thi', models.CharField(choices=[(b'DA_THI', b'\xc4\x90\xc3\xa3 thi'), (b'VANG_CO_LD', b'V\xe1\xba\xafng c\xc3\xb3 l\xc3\xbd do'), (b'VANG_KO_LD', b'V\xe1\xba\xafng kh\xc3\xb4ng l\xc3\xbd do')], default=b'DA_THI', max_length=20, verbose_name=b'Tr\xe1\xba\xa1ng th\xc3\xa1i thi')),
                ('diem', models.CommaSeparatedIntegerField(blank=True, max_length=5, null=True, verbose_name=b'\xc4\x90i\xe1\xbb\x83m')),
            ],
            options={
                'verbose_name': '\u0110i\u1ec3m',
                'verbose_name_plural': 'B\u1ea3ng \u0111i\u1ec3m',
            },
        ),
        migrations.CreateModel(
            name='DoiTuong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dt', models.CharField(help_text=b'M\xc3\xa3 kh\xc3\xb4ng qu\xc3\xa1 10 k\xc3\xbd t\xe1\xbb\xb1', max_length=10, unique=True, verbose_name=b'M\xc3\xa3 \xc4\x91\xe1\xbb\x91i t\xc6\xb0\xe1\xbb\xa3ng')),
                ('ten_dt', models.CharField(max_length=50, unique=True, verbose_name=b'T\xc3\xaan \xc4\x91\xe1\xbb\x91i t\xc6\xb0\xe1\xbb\xa3ng')),
                ('cach_lam_tron', models.CharField(choices=[(b'Lam tron cach 1', b'C\xc3\xa1ch 1'), (b'Lam tron cach 2', b'C\xc3\xa1ch 2')], default=b'Lam tron cach 1', max_length=20, verbose_name=b'C\xc3\xa1ch l\xc3\xa0m tr\xc3\xb2n')),
            ],
            options={
                'verbose_name': '\u0110\u1ed1i t\u01b0\u1ee3ng',
                'verbose_name_plural': 'Danh s\xe1ch \u0111\u1ed1i t\u01b0\u1ee3ng',
            },
        ),
        migrations.CreateModel(
            name='ImportSinhVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_file', models.FileField(blank=True, null=True, upload_to=b'tmp', verbose_name=b'Ch\xe1\xbb\x8dn file (.xlsx) d\xe1\xbb\xaf li\xe1\xbb\x87u')),
            ],
            options={
                'verbose_name': 'Nh\u1eadp danh s\xe1ch sinh vi\xean t\u1eeb file .xlsx',
                'verbose_name_plural': 'Nh\u1eadp danh s\xe1ch sinh vi\xean t\u1eeb file .xlsx',
            },
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=5, unique=True, verbose_name=b'M\xc3\xa3 l\xe1\xbb\x9bp')),
                ('ten_lop', models.CharField(max_length=200, unique=True, verbose_name=b'L\xe1\xbb\x9bp')),
                ('si_so', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'S\xc4\xa9 s\xe1\xbb\x91')),
                ('doi_tuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.DoiTuong', verbose_name=b'\xc4\x90\xe1\xbb\x91i t\xc6\xb0\xe1\xbb\xa3ng')),
            ],
            options={
                'verbose_name': 'L\u1edbp',
                'verbose_name_plural': 'Danh s\xe1ch l\u1edbp',
            },
        ),
        migrations.CreateModel(
            name='MonThi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon_thi', models.CharField(max_length=10, unique=True, verbose_name=b'M\xc3\xa3 m\xc3\xb4n thi')),
                ('ten_mon_thi', models.CharField(max_length=200, unique=True, verbose_name=b'M\xc3\xb4n thi')),
                ('so_chuong', models.PositiveIntegerField(default=5, verbose_name=b'S\xe1\xbb\x91 ch\xc6\xb0\xc6\xa1ng')),
                ('so_dvht', models.PositiveIntegerField(default=3, verbose_name=b'S\xe1\xbb\x91 \xc4\x91\xc6\xa1n v\xe1\xbb\x8b h\xe1\xbb\x8dc tr\xc3\xacnh')),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.DonVi', verbose_name=b'Khoa')),
            ],
            options={
                'verbose_name': 'M\xf4n thi',
                'verbose_name_plural': 'Danh s\xe1ch m\xf4n thi',
            },
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sv', models.CharField(max_length=15, unique=True, verbose_name=b'M\xc3\xa3 sinh vi\xc3\xaan')),
                ('ho_dem', models.CharField(max_length=50, verbose_name=b'H\xe1\xbb\x8d \xc4\x91\xe1\xbb\x87m')),
                ('ten', models.CharField(max_length=10, verbose_name=b'T\xc3\xaan')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.Lop', verbose_name=b'L\xe1\xbb\x9bp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinh vi\xean',
                'verbose_name_plural': 'Danh s\xe1ch sinh vi\xean',
            },
        ),
        migrations.AddField(
            model_name='importsinhvien',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.Lop', verbose_name=b'L\xe1\xbb\x9bp'),
        ),
        migrations.AddField(
            model_name='diem',
            name='mon_thi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.MonThi', verbose_name=b'M\xc3\xb4n thi'),
        ),
        migrations.AddField(
            model_name='diem',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.SinhVien', verbose_name=b'Sinh vi\xc3\xaan'),
        ),
        migrations.AlterUniqueTogether(
            name='diem',
            unique_together=set([('sinh_vien', 'mon_thi')]),
        ),
    ]
