# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daotao', '0001_initial'),
        ('common', '0001_initial'),
        ('diem', '0002_auto_20160728_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamDiemSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.FloatField(default=0.0, verbose_name='\u0110i\u1ec3m')),
                ('loai_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diem.LoaiDiem', verbose_name='Lo\u1ea1i \u0111i\u1ec3m')),
            ],
            options={
                'verbose_name': '\u0110i\u1ec3m sinh vi\xean',
                'verbose_name_plural': '\u0110i\u1ec3m sinh vi\xean',
            },
        ),
        migrations.CreateModel(
            name='NhapDiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[(1, b'Ch\xc6\xb0a c\xc3\xb3 \xc4\x91i\xe1\xbb\x83m'), (2, b'Ch\xe1\xba\xa5m \xc4\x91i\xe1\xbb\x83m d\xe1\xbb\x8dc \xc4\x91\xc6\xb0\xe1\xbb\x9dng xong'), (3, b'Ch\xe1\xba\xa5m \xc4\x91i\xe1\xbb\x83m 1 xong'), (4, b'Ch\xe1\xba\xa5m \xc4\x91i\xe1\xbb\x83m 2 xong'), (5, b'Ch\xe1\xba\xa5m \xc4\x91i\xe1\xbb\x83m 3 xong')], default=1, max_length=30, verbose_name='Tr\u1ea1ng th\xe1i')),
                ('khthi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.KHThiBase', verbose_name='Ca thi')),
            ],
            options={
                'verbose_name': 'Nh\u1eadp \u0111i\u1ec3m sinh vi\xean',
                'verbose_name_plural': 'Nh\u1eadp \u0111i\u1ec3m sinh vi\xean',
            },
        ),
        migrations.AddField(
            model_name='chamdiemsv',
            name='nhap_diem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamthi.NhapDiem'),
        ),
        migrations.AddField(
            model_name='chamdiemsv',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.SinhVien', verbose_name='Sinh vi\xean'),
        ),
    ]
