# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamthi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhapdiem',
            options={'permissions': (('duoc_phep_nhap_diem_doc_duong', 'Ng\u01b0\u1eddi d\xf9ng \u0111\u01b0\u1ee3c ph\xe9p nh\u1eadp \u0111i\u1ec3m d\u1ecdc \u0111\u01b0\u1eddng'), ('duoc_phep_nhap_diem_1', 'Cho ph\xe9p gi\xe1o vi\xean ch\u1ea5m thi 1 nh\u1eadp \u0111i\u1ec3m'), ('duoc_phep_nhap_diem_2', 'Cho ph\xe9p gi\xe1o vi\xean ch\u1ea5m thi 2 nh\u1eadp \u0111i\u1ec3m'), ('duoc_phep_nhap_diem_3', 'Cho ph\xe9p gi\xe1o vi\xean ch\u1ea5m thi 3 nh\u1eadp \u0111i\u1ec3m')), 'verbose_name': 'Nh\u1eadp \u0111i\u1ec3m sinh vi\xean', 'verbose_name_plural': 'Nh\u1eadp \u0111i\u1ec3m sinh vi\xean'},
        ),
        migrations.AlterField(
            model_name='nhapdiem',
            name='trang_thai',
            field=models.CharField(choices=[(b'CHUA_CO_DIEM', b'Ch\xc6\xb0a c\xc3\xb3 \xc4\x91i\xe1\xbb\x83m'), (b'DOC_DUONG', b'Ch\xe1\xba\xa5m \xc4\x91i\xe1\xbb\x83m d\xe1\xbb\x8dc \xc4\x91\xc6\xb0\xe1\xbb\x9dng xong'), (b'CHAM_DIEM_1', b'Ch\xe1\xba\xa5m \xc4\x91i\xe1\xbb\x83m 1 xong'), (b'CHAM_DIEM_2', b'Ch\xe1\xba\xa5m \xc4\x91i\xe1\xbb\x83m 2 xong'), (b'CHAM_DIEM_3', b'Ch\xe1\xba\xa5m \xc4\x91i\xe1\xbb\x83m 3 xong')], default=b'CHUA_CO_DIEM', max_length=30, verbose_name='Tr\u1ea1ng th\xe1i'),
        ),
    ]
