# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daotao', '0001_initial'),
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KHThiBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, verbose_name='T\xean')),
                ('nam_hoc', models.CharField(help_text='Nh\u1eadp n\u0103m h\u1ecdc theo \u0111\u1ecbnh d\u1ea1ng XXXX-XXXX. V\xed d\u1ee5 2015-2016', max_length=9, verbose_name='N\u0103m h\u1ecdc')),
                ('hoc_ky', models.CharField(choices=[(b'HK1', b'H\xe1\xbb\x8dc k\xe1\xbb\xb3 1'), (b'HK2', b'H\xe1\xbb\x8dc k\xe1\xbb\xb3 2')], default=b'HK1', max_length=3, verbose_name='H\u1ecdc k\u1ef3')),
                ('ngay_thi', models.DateField(default=django.utils.timezone.now, verbose_name=b'Ng\xc3\xa0y thi')),
                ('tg_bat_dau', models.TimeField(default=django.utils.timezone.now, verbose_name=b'Th\xe1\xbb\x9di gian b\xe1\xba\xaft \xc4\x91\xe1\xba\xa7u')),
                ('tg_thi', models.PositiveIntegerField(default=30, help_text=b'Nh\xe1\xba\xadp th\xe1\xbb\x9di gian thi t\xc3\xadnh b\xe1\xba\xb1ng \xc4\x91\xc6\xa1n v\xe1\xbb\x8b ph\xc3\xbat', verbose_name=b'Th\xe1\xbb\x9di gian thi (ph\xc3\xbat)')),
                ('doi_tuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.DoiTuong', verbose_name='\u0110\u1ed1i t\u01b0\u1ee3ng')),
                ('ds_giamthi', models.ManyToManyField(related_name='khthibase_giamthi_khthi', to='hrm.GiaoVien', verbose_name='Danh s\xe1ch gi\xe1m th\u1ecb coi thi')),
                ('ds_thisinh', models.ManyToManyField(related_name='khthibase_sinhvien_khthi', to='daotao.SinhVien', verbose_name='Danh s\xe1ch th\xed sinh')),
                ('mon_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khthibase_monthi_cathi', to='daotao.MonThi', verbose_name=b'M\xc3\xb4n thi')),
                ('nguoi_boc_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.GiaoVien', verbose_name=b'Ng\xc6\xb0\xe1\xbb\x9di b\xe1\xbb\x91c \xc4\x91\xe1\xbb\x81')),
            ],
            options={
                'verbose_name': 'K\u1ebf ho\u1ea1ch thi - b\u1ed1c \u0111\u1ec1',
                'verbose_name_plural': 'K\u1ebf ho\u1ea1ch thi - b\u1ed1c \u0111\u1ec1',
                'permissions': (('duoc_phep_boc_de', 'Ng\u01b0\u1eddi d\xf9ng \u0111\u01b0\u1ee3c ph\xe9p b\u1ed1c \u0111\u1ec1'), ('duoc_phep_xem_va_in_de', 'Ng\u01b0\u1eddi d\xf9ng \u0111\u01b0\u1ee3c ph\xe9p xem v\xe0 in \u0111\u1ec1')),
            },
        ),
    ]
