# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonVi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dv', models.CharField(help_text=b'M\xc3\xa3 \xc4\x91\xc6\xa1n v\xe1\xbb\x8b kh\xc3\xb4ng qu\xc3\xa1 5 k\xc3\xbd t\xe1\xbb\xb1', max_length=5, unique=True, verbose_name=b'M\xc3\xa3 \xc4\x91\xc6\xa1n v\xe1\xbb\x8b')),
                ('ten_dv', models.CharField(max_length=200, unique=True, verbose_name=b'T\xc3\xaan \xc4\x91\xc6\xa1n v\xe1\xbb\x8b')),
                ('cha_dv', models.ForeignKey(blank=True, help_text=b'\xc4\x90\xc6\xa1n v\xe1\xbb\x8b c\xe1\xba\xa5p tr\xc3\xaan tr\xe1\xbb\xb1c ti\xe1\xba\xbfp', null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.DonVi', verbose_name=b'\xc4\x90\xc6\xa1n v\xe1\xbb\x8b c\xe1\xba\xa5p tr\xc3\xaan')),
            ],
            options={
                'verbose_name': '\u0110\u01a1n v\u1ecb',
                'verbose_name_plural': 'Danh s\xe1ch \u0111\u01a1n v\u1ecb',
            },
        ),
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_so', models.PositiveIntegerField(unique=True, verbose_name=b'M\xc3\xa3 s\xe1\xbb\x91')),
                ('ho_ten', models.CharField(max_length=50, verbose_name=b'H\xe1\xbb\x8d v\xc3\xa0 t\xc3\xaan')),
                ('don_vi', models.ForeignKey(help_text=b'\xc4\x90\xc6\xa1n v\xe1\xbb\x8b qu\xe1\xba\xa3n l\xc3\xbd tr\xe1\xbb\xb1c ti\xe1\xba\xbfp', on_delete=django.db.models.deletion.CASCADE, to='hrm.DonVi', verbose_name=b'\xc4\x90\xc6\xa1n v\xe1\xbb\x8b')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gi\xe1o vi\xean',
                'verbose_name_plural': 'Danh s\xe1ch gi\xe1o vi\xean',
            },
        ),
    ]
