# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0002_auto_20160728_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaidiem',
            name='nhap_diem_theo_so_phach',
            field=models.BooleanField(default=True, verbose_name='Nh\u1eadp \u0111i\u1ec3m theo s\u1ed1 ph\xe1ch'),
        ),
    ]
