# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0003_loaidiem_nhap_diem_theo_so_phach'),
    ]

    operations = [
        migrations.AddField(
            model_name='tylediem',
            name='thu_tu_cham',
            field=models.PositiveIntegerField(default=1, help_text='Th\u1ee9 t\u1ef1 cho ph\xe9p nh\u1eadp \u0111i\u1ec3m, nh\u1eadp gi\xe1 tr\u1ecb t\u1eeb 1', verbose_name='Th\u1ee9 t\u1ef1 nh\u1eadp \u0111i\u1ec3m'),
        ),
    ]
