# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0004_tylediem_thu_tu_cham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tylediem',
            name='doi_tuong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.DoiTuong', verbose_name='\u0110\u1ed1i t\u01b0\u1ee3ng'),
        ),
        migrations.AlterUniqueTogether(
            name='ketquathi',
            unique_together=set([]),
        ),
    ]
