# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daotao', '0001_initial'),
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_so', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'M\xc3\xa3 b\xe1\xbb\x99 \xc4\x91\xe1\xbb\x81')),
                ('ngay_tao', models.DateField(default=django.utils.timezone.now, verbose_name=b'Ng\xc3\xa0y t\xe1\xba\xa1o')),
                ('doi_tuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.DoiTuong', verbose_name=b'\xc4\x90\xe1\xbb\x91i t\xc6\xb0\xe1\xbb\xa3ng thi')),
                ('mon_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.MonThi', verbose_name=b'M\xc3\xb4n thi')),
            ],
            options={
                'verbose_name': 'B\u1ed9 \u0111\u1ec1 thi t\u1ef1 lu\u1eadn',
                'verbose_name_plural': 'B\u1ed9 \u0111\u1ec1 thi t\u1ef1 lu\u1eadn',
            },
        ),
        migrations.CreateModel(
            name='CaThi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ca_thi', models.CharField(max_length=100, verbose_name=b'T\xc3\xaan ca thi')),
                ('nam_hoc', models.CharField(help_text=b'Nh\xe1\xba\xadp n\xc4\x83m h\xe1\xbb\x8dc theo \xc4\x91\xe1\xbb\x8bnh d\xe1\xba\xa1ng XXXX-XXXX. V\xc3\xad d\xe1\xbb\xa5 2015-2016', max_length=9, verbose_name=b'N\xc4\x83m h\xe1\xbb\x8dc')),
                ('hoc_ky', models.CharField(choices=[(b'HK1', b'H\xe1\xbb\x8dc k\xe1\xbb\xb3 1'), (b'HK2', b'H\xe1\xbb\x8dc k\xe1\xbb\xb3 2')], default=b'HK1', max_length=3, verbose_name=b'H\xe1\xbb\x8dc k\xe1\xbb\xb3')),
                ('ngay_thi', models.DateField(verbose_name=b'Ng\xc3\xa0y thi')),
                ('so_de_thi', models.PositiveIntegerField(default=1, help_text='S\u1ed1 \u0111\u1ec1 thi l\xe0 s\u1ed1 nguy\xean d\u01b0\u01a1ng, l\u1edbn h\u01a1n 0', verbose_name=b'S\xe1\xbb\x91 \xc4\x91\xe1\xbb\x81 thi')),
                ('doi_tuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.DoiTuong', verbose_name=b'\xc4\x90\xe1\xbb\x91i t\xc6\xb0\xe1\xbb\xa3ng')),
            ],
            options={
                'verbose_name': 'K\u1ebf ho\u1ea1ch thi - b\u1ed1c \u0111\u1ec1',
                'verbose_name_plural': 'K\u1ebf ho\u1ea1ch thi - b\u1ed1c \u0111\u1ec1',
            },
        ),
        migrations.CreateModel(
            name='DeThi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_de_thi', models.CharField(max_length=10, verbose_name=b'M\xc3\xa3 \xc4\x91\xe1\xbb\x81 thi')),
                ('de_thi', models.FileField(blank=True, null=True, upload_to=b'uploads/essay/%Y/%m/%d', verbose_name=b'\xc4\x90\xe1\xbb\x81 thi')),
                ('dap_an', models.FileField(blank=True, null=True, upload_to=b'uploads/essay/%Y/%m/%d', verbose_name=b'\xc4\x90\xc3\xa1p \xc3\xa1n')),
                ('ngan_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuluan.BoDe', verbose_name=b'Ng\xc3\xa2n h\xc3\xa0ng')),
            ],
            options={
                'verbose_name': '\u0110\u1ec1 thi t\u1ef1 lu\u1eadn',
                'verbose_name_plural': 'Danh s\xe1ch \u0111\u1ec1 thi t\u1ef1 lu\u1eadn',
            },
        ),
        migrations.AddField(
            model_name='cathi',
            name='ds_de_thi',
            field=models.ManyToManyField(blank=True, to='tuluan.DeThi', verbose_name='DT'),
        ),
        migrations.AddField(
            model_name='cathi',
            name='giam_thi',
            field=models.ManyToManyField(to='hrm.GiaoVien', verbose_name='Danh s\xe1ch gi\xe1m th\u1ecb coi thi'),
        ),
        migrations.AddField(
            model_name='cathi',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.Lop', verbose_name=b'L\xe1\xbb\x9bp'),
        ),
        migrations.AddField(
            model_name='cathi',
            name='mon_thi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.MonThi', verbose_name=b'M\xc3\xb4n thi'),
        ),
    ]
