# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('tuluan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KHThiTuLuan',
            fields=[
                ('khthibase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.KHThiBase')),
                ('so_de_thi', models.PositiveIntegerField(default=1, help_text='S\u1ed1 \u0111\u1ec1 thi l\xe0 s\u1ed1 nguy\xean d\u01b0\u01a1ng, l\u1edbn h\u01a1n 0', verbose_name=b'S\xe1\xbb\x91 \xc4\x91\xe1\xbb\x81 thi')),
                ('ds_de_thi', models.ManyToManyField(blank=True, to='tuluan.DeThi', verbose_name='DT')),
            ],
            options={
                'verbose_name': 'K\u1ebf ho\u1ea1ch thi - b\u1ed1c \u0111\u1ec1',
                'verbose_name_plural': 'K\u1ebf ho\u1ea1ch thi - b\u1ed1c \u0111\u1ec1',
            },
            bases=('common.khthibase',),
        ),
        migrations.RemoveField(
            model_name='cathi',
            name='doi_tuong',
        ),
        migrations.RemoveField(
            model_name='cathi',
            name='ds_de_thi',
        ),
        migrations.RemoveField(
            model_name='cathi',
            name='giam_thi',
        ),
        migrations.RemoveField(
            model_name='cathi',
            name='lop',
        ),
        migrations.RemoveField(
            model_name='cathi',
            name='mon_thi',
        ),
        migrations.DeleteModel(
            name='CaThi',
        ),
    ]
