# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daotao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dapAn', models.CharField(max_length=1000, verbose_name=b'Ph\xc6\xb0\xc6\xa1ng \xc3\xa1n tr\xe1\xba\xa3 l\xe1\xbb\x9di')),
                ('isCorrect', models.BooleanField(default=False, help_text=b'Ph\xc6\xb0\xc6\xa1ng \xc3\xa1n \xc4\x91\xc3\xbang?', verbose_name=b'L\xc3\xa0 ph\xc6\xb0\xc6\xa1ng \xc3\xa1n \xc4\x91\xc3\xbang')),
            ],
            options={
                'verbose_name': 'Ph\u01b0\u01a1ng \xe1n tr\u1ea3 l\u1eddi',
                'verbose_name_plural': 'Danh s\xe1ch ph\u01b0\u01a1ng \xe1n tr\u1ea3 l\u1eddi',
            },
        ),
        migrations.CreateModel(
            name='BaiThi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_cauhoi', models.TextField(default={})),
                ('tra_loi', models.TextField(default={})),
                ('diem', models.FloatField(verbose_name=b'\xc4\x90i\xe1\xbb\x83m')),
                ('is_finished', models.BooleanField(default=False, verbose_name=b'Ho\xc3\xa0n th\xc3\xa0nh')),
            ],
            options={
                'verbose_name': 'B\xe0i thi',
                'verbose_name_plural': 'B\xe0i thi',
            },
        ),
        migrations.CreateModel(
            name='ImportMCQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_file', models.FileField(blank=True, null=True, upload_to=b'tmp', verbose_name=b'Ch\xe1\xbb\x8dn file d\xe1\xbb\xaf li\xe1\xbb\x87u')),
                ('doi_tuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.DoiTuong', verbose_name=b'\xc4\x90\xe1\xbb\x91i t\xc6\xb0\xe1\xbb\xa3ng')),
                ('mon_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.MonThi', verbose_name=b'M\xc3\xb4n thi')),
            ],
            options={
                'verbose_name': 'Nh\u1eadp danh s\xe1ch c\xe2u h\u1ecfi Multiple Choice t\u1eeb file',
                'verbose_name_plural': 'Nh\u1eadp danh s\xe1ch c\xe2u h\u1ecfi Multiple Choice t\u1eeb file',
            },
        ),
        migrations.CreateModel(
            name='KHThi',
            fields=[
                ('khthibase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.KHThiBase')),
                ('tg_thi_batdau', models.TimeField(default=django.utils.timezone.now)),
                ('de_thi_id', models.PositiveIntegerField(null=True)),
                ('de_thi', models.TextField(default=b'{}')),
                ('dap_an', models.TextField(default=b'{}')),
                ('tao_moi_de_thi', models.BooleanField(default=True, verbose_name=b'T\xe1\xba\xa1o m\xe1\xbb\x9bi \xc4\x91\xe1\xbb\x81 thi cho c\xc3\xa1c sinh vi\xc3\xaan')),
                ('so_luong_de', models.PositiveIntegerField(default=0, help_text='Nh\u1eadp gi\xe1 tr\u1ecb >= 0, nh\u1eadp 0 s\u1ebd sinh m\u1ed7i sinh vi\xean m\u1ed9t \u0111\u1ec1', verbose_name=b'S\xe1\xbb\x91 l\xc6\xb0\xe1\xbb\xa3ng \xc4\x91\xe1\xbb\x81 thi t\xe1\xba\xa1o ra')),
                ('ghichu', models.TextField(blank=True, null=True, verbose_name=b'Ghi ch\xc3\xba')),
                ('trang_thai', models.CharField(blank=True, choices=[(b'CHUA_THI', b'Ch\xc6\xb0a thi'), (b'DANG_THI', b'\xc4\x90ang thi'), (b'DA_THI', b'\xc4\x90\xc3\xa3 thi')], default=b'CHUA_THI', max_length=30, null=True, verbose_name=b'Tr\xe1\xba\xa1ng th\xc3\xa1i')),
            ],
            bases=('common.khthibase',),
        ),
        migrations.CreateModel(
            name='LoggedUser',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LogSinhDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuong', models.PositiveIntegerField(default=20, verbose_name=b'S\xe1\xbb\x91 l\xc6\xb0\xe1\xbb\xa3ng')),
                ('ngayTao', models.DateField(verbose_name=b'Ng\xc3\xa0y t\xe1\xba\xa1o')),
                ('doiTuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.DoiTuong', verbose_name=b'\xc4\x90\xe1\xbb\x91i t\xc6\xb0\xe1\xbb\xa3ng')),
                ('monHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.MonThi', verbose_name=b'M\xc3\xb4n thi')),
                ('nguoiTao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Ng\xc6\xb0\xe1\xbb\x9di t\xe1\xba\xa1o')),
            ],
            options={
                'verbose_name': 'Sinh \u0111\u1ec1 thi',
                'verbose_name_plural': 'Sinh \u0111\u1ec1 thi',
            },
        ),
        migrations.CreateModel(
            name='Lop_CaThi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_sinhvien', models.ManyToManyField(to='daotao.SinhVien')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.Lop', verbose_name=b'L\xe1\xbb\x9bp thi')),
            ],
        ),
        migrations.CreateModel(
            name='NganHangDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maDeThi', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'M\xc3\xa3 \xc4\x91\xe1\xbb\x81 thi')),
                ('questions', models.CommaSeparatedIntegerField(default=1, max_length=50, verbose_name=b'Danh s\xc3\xa1ch c\xc3\xa2u h\xe1\xbb\x8fi')),
                ('daDuyet', models.BooleanField(default=False, verbose_name=b'\xc4\x90\xc3\xa3 duy\xe1\xbb\x87t')),
                ('ngay_tao', models.DateField(verbose_name=b'Ng\xc3\xa0y t\xe1\xba\xa1o')),
                ('logSinhDe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracnghiem.LogSinhDe', verbose_name=b'C\xe1\xba\xa5u h\xc3\xacnh sinh \xc4\x91\xe1\xbb\x81')),
            ],
            options={
                'verbose_name': 'Ng\xe2n h\xe0ng \u0111\u1ec1 thi',
                'verbose_name_plural': 'Ng\xe2n h\xe0ng \u0111\u1ec1 thi',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maCauHoi', models.CharField(max_length=20, unique=True, verbose_name=b'M\xc3\xa3 c\xc3\xa2u h\xe1\xbb\x8fi')),
                ('loaiCauHoi', models.CharField(choices=[(b'TF', b'C\xc3\xa2u h\xe1\xbb\x8fi \xc4\x90\xc3\xbang - Sai'), (b'MC', b'C\xc3\xa2u h\xe1\xbb\x8fi Multiple Choice'), (b'ESSAY', b'C\xc3\xa2u h\xe1\xbb\x8fi t\xe1\xbb\xb1 lu\xe1\xba\xadn')], default=b'MC', max_length=5, verbose_name=b'Lo\xe1\xba\xa1i c\xc3\xa2u h\xe1\xbb\x8fi')),
                ('level', models.PositiveIntegerField(default=1)),
                ('thuocChuong', models.CommaSeparatedIntegerField(default=1, max_length=50, verbose_name=b'Ph\xe1\xbb\xa7 c\xc3\xa1c ch\xc6\xb0\xc6\xa1ng')),
                ('noiDung', models.TextField(max_length=1000, verbose_name=b'C\xc3\xa2u h\xe1\xbb\x8fi')),
                ('diem', models.FloatField(default=1.0, verbose_name=b'\xc4\x90i\xe1\xbb\x83m')),
                ('figure', models.ImageField(blank=True, null=True, upload_to=b'uploads/figs/%Y/%m/%d', verbose_name=b'\xe1\xba\xa2nh')),
            ],
            options={
                'verbose_name': 'C\xe2u h\u1ecfi',
                'verbose_name_plural': 'Danh s\xe1ch c\xe2u h\u1ecfi',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name=b'Nh\xc3\xb3m c\xc3\xa2u h\xe1\xbb\x8fi')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'Ghi ch\xc3\xba')),
            ],
            options={
                'verbose_name': 'Nh\xf3m c\xe2u h\u1ecfi',
                'verbose_name_plural': 'Danh s\xe1ch nh\xf3m c\xe2u h\u1ecfi',
            },
        ),
        migrations.CreateModel(
            name='SinhDeConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaiCauHoi', models.CharField(choices=[(b'TF', b'C\xc3\xa2u h\xe1\xbb\x8fi \xc4\x90\xc3\xbang - Sai'), (b'MC', b'C\xc3\xa2u h\xe1\xbb\x8fi Multiple Choice'), (b'ESSAY', b'C\xc3\xa2u h\xe1\xbb\x8fi t\xe1\xbb\xb1 lu\xe1\xba\xadn')], default=b'MC', max_length=5, verbose_name=b'Lo\xe1\xba\xa1i c\xc3\xa2u h\xe1\xbb\x8fi')),
                ('soLuong', models.PositiveIntegerField(default=1, verbose_name=b's\xe1\xbb\x91 c\xc3\xa2u h\xe1\xbb\x8fi')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracnghiem.QuestionGroup', verbose_name=b'Nh\xc3\xb3m c\xc3\xa2u h\xe1\xbb\x8fi')),
                ('logSinhDe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracnghiem.LogSinhDe', verbose_name=b'C\xe1\xba\xa5u h\xc3\xacnh sinh \xc4\x91\xe1\xbb\x81')),
            ],
            options={
                'verbose_name': 'C\u1ea5u h\xecnh ca thi',
                'verbose_name_plural': 'C\u1ea5u h\xecnh ca thi',
            },
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracnghiem.Question')),
                ('answerOrder', models.CharField(blank=True, choices=[(b'CONTENT', b'N\xe1\xbb\x99i dung'), (b'RANDOM', b'Ng\xe1\xba\xabu nhi\xc3\xaan'), (b'NONE', b'None')], max_length=30, null=True, verbose_name=b'Th\xe1\xbb\xa9 t\xe1\xbb\xb1 hi\xe1\xbb\x83n th\xe1\xbb\x8b c\xc3\xa2u tr\xe1\xba\xa3 l\xe1\xbb\x9di')),
            ],
            options={
                'verbose_name': 'C\xe2u h\u1ecfi lo\u1ea1i Multiple choice',
                'verbose_name_plural': 'Danh s\xe1ch c\xe2u h\u1ecfi lo\u1ea1i Multiple choice',
            },
            bases=('tracnghiem.question',),
        ),
        migrations.CreateModel(
            name='TFQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracnghiem.Question')),
                ('isTrue', models.BooleanField(default=False, verbose_name=b'L\xc3\xa0 \xc4\x91\xc3\xa1p \xc3\xa1n \xc4\x91\xc3\xbang?')),
            ],
            options={
                'ordering': ['monHoc'],
                'verbose_name': 'C\xe2u h\u1ecfi \u0110\xfang/Sai',
                'verbose_name_plural': 'Danh s\xe1ch c\xe2u h\u1ecfi \u0110\xfang/Sai',
            },
            bases=('tracnghiem.question',),
        ),
        migrations.AddField(
            model_name='question',
            name='doiTuong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.DoiTuong', verbose_name=b'\xc4\x90\xe1\xbb\x91i t\xc6\xb0\xe1\xbb\xa3ng'),
        ),
        migrations.AddField(
            model_name='question',
            name='monHoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.MonThi', verbose_name=b'M\xc3\xb4n thi'),
        ),
        migrations.AddField(
            model_name='question',
            name='prior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_knowledge', to='tracnghiem.QuestionGroup', verbose_name=b'Nh\xc3\xb3m c\xc3\xa2u h\xe1\xbb\x8fi'),
        ),
        migrations.AddField(
            model_name='baithi',
            name='khthi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracnghiem.KHThi'),
        ),
        migrations.AddField(
            model_name='baithi',
            name='thi_sinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daotao.SinhVien', to_field=b'ma_sv', verbose_name=b'Sinh vi\xc3\xaan'),
        ),
        migrations.AlterUniqueTogether(
            name='baithi',
            unique_together=set([('khthi', 'thi_sinh')]),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracnghiem.MCQuestion', verbose_name=b'C\xc3\xa2u h\xe1\xbb\x8fi'),
        ),
    ]
