# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracnghiem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khthi',
            options={'permissions': (('duoc_phep_boc_de', 'Ng\u01b0\u1eddi d\xf9ng \u0111\u01b0\u1ee3c ph\xe9p b\u1ed1c \u0111\u1ec1'), ('duoc_phep_xem_va_in_de', 'Ng\u01b0\u1eddi d\xf9ng \u0111\u01b0\u1ee3c ph\xe9p xem v\xe0 in \u0111\u1ec1')), 'verbose_name': 'K\u1ebf ho\u1ea1ch thi - b\u1ed1c \u0111\u1ec1', 'verbose_name_plural': 'K\u1ebf ho\u1ea1ch thi - b\u1ed1c \u0111\u1ec1'},
        ),
    ]
